customers:
  - info :                 'Huber'
    market_order_name:     'customername1'
    market_order_filename: ''
    market_order_path:     ''
  - info :                 'Mustermann'
    market_order_name:     'customername2'
    market_order_filename: ''
    market_order_path:     ''
  - info :                 'Maier'
    market_order_name:     'customername42'
    market_order_filename: ''
    market_order_path:     ''
  - info :                 'Schneider'
    market_order_name:     'customername69'
    market_order_filename: ''
    market_order_path:     ''
